name: Documentation

on:
  push:

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Zeek RPM
      run: sudo $GITHUB_WORKSPACE/.ci_scripts/install_zeek.sh "zeek"

    - name: Install Sphinx theme
      run: sudo pip3 install -U sphinx_rtd_theme

    - name: Ensure Zeek was correctly installed
      run: |
        source $GITHUB_WORKSPACE/.ci_scripts/set_env_path.sh
        zeek --version

    - name: Generate docs
      run: |
        source $GITHUB_WORKSPACE/.ci_scripts/set_env_path.sh
        make -C $GITHUB_WORKSPACE/docs

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/html
